# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      # Verify formatting using Flutter (recommended for Flutter projects)
      - name: Check formatting
        run: dart format --set-exit-if-changed .
        
      # Verify Dependencies
      - name: Verify dependencies
        run: dart pub deps --verify-unused
        
      - name: Build Runner
        run: dart run build_runner build --delete-conflicting-outputs

      # Analyze project source
      - name: Analyze project source
        run: flutter analyze

      # Run Flutter tests
      - name: Run tests
        run: flutter test
